package semana6;

import java.util.Random;

public class Juego extends javax.swing.JFrame {

    Random random = new Random();

    static String palabras[] = {"Honduras", "Rojo", "Profeta", "Pizza", "Hamburguesa", "Panama", "Telefono", "Lentes", "Manzana", "Pera"};
    int posicion = random.nextInt(0, 10);
    String palabraEscondida;
    char progreso[];
    int intentos = 5;

    public Juego() {
        initComponents();

        palabraEscondida = palabras[posicion].toUpperCase();
        progreso = new char[palabraEscondida.length()];

        for (int i = 0; i < progreso.length; i++) {
            progreso[i] = '_';
        }

        String texto = "";
        for (int i = 0; i < progreso.length; i++) {
            texto += progreso[i] + " ";
        }
        palabraGenerada.setText(texto);
        labelIntentos.setText("Intentos Restantes: "+intentos);
        vfIntento.setText("");
        labelResultado.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloAhorcado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        letraAhorcado = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        palabraGenerada = new javax.swing.JLabel();
        labelPalabra = new javax.swing.JLabel();
        labelIntentos = new javax.swing.JLabel();
        vfIntento = new javax.swing.JLabel();
        labelResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloAhorcado.setFont(new java.awt.Font("Kefa", 1, 24)); // NOI18N
        tituloAhorcado.setText("Ahorcado");

        jLabel1.setText("Ingresa una letra:");

        letraAhorcado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraAhorcadoActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        palabraGenerada.setText("Palabra");

        labelPalabra.setText("Palabra:");

        labelIntentos.setText("Intentos Restantes: ");

        vfIntento.setText("verificacion intento");

        labelResultado.setFont(new java.awt.Font("Kefa", 1, 24)); // NOI18N
        labelResultado.setText("resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(letraAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPalabra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(palabraGenerada))
                    .addComponent(vfIntento)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(tituloAhorcado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(tituloAhorcado)
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letraAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAceptar))
                .addGap(18, 18, 18)
                .addComponent(vfIntento)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIntentos)
                    .addComponent(labelResultado))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPalabra)
                    .addComponent(palabraGenerada))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void letraAhorcadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraAhorcadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letraAhorcadoActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        
        Menu menu = new Menu();
        String entrada = letraAhorcado.getText().toUpperCase();
        boolean acierto = false;
        letraAhorcado.setText("");

        if (entrada.length() == 1) {
            char letra = entrada.charAt(0);

            for (int i = 0; i < palabraEscondida.length(); i++) {
                if (palabraEscondida.charAt(i) == letra) {
                    progreso[i] = letra;
                    acierto = true;
                }
            }
            
            if(!acierto){
                intentos--;
                vfIntento.setText("No le pegaste al caracter!");
            }else{
                vfIntento.setText("Le pegaste al caracter!");
            }

            String texto = "";
            String verificacion = "";
            for (int i = 0; i < progreso.length; i++) {
                texto += progreso[i] + " ";
                verificacion += progreso[i];
            }

            palabraGenerada.setText(texto);
            
            if(intentos == 0){
                botonAceptar.setEnabled(false);
                letraAhorcado.setEnabled(false);
                labelResultado.setText("Perdiste!");
                javax.swing.Timer timer = new javax.swing.Timer(2000, e -> {
                    dispose();
                    menu.setLocationRelativeTo(this);
                    menu.setVisible(true);
                });
                timer.setRepeats(false);
                timer.start();
            }

            if (verificacion.equalsIgnoreCase(palabras[posicion].toUpperCase())) {
                botonAceptar.setEnabled(false);
                letraAhorcado.setEnabled(false);
                labelResultado.setText("Ganaste!");

                javax.swing.Timer timer = new javax.swing.Timer(2000, e -> {
                    dispose();
                    menu.setLocationRelativeTo(this);
                    menu.setVisible(true);
                });
                timer.setRepeats(false);
                timer.start();
            }
            labelIntentos.setText("Intentos Restantes: "+intentos);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel labelIntentos;
    private static javax.swing.JLabel labelPalabra;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JTextField letraAhorcado;
    private static javax.swing.JLabel palabraGenerada;
    private javax.swing.JLabel tituloAhorcado;
    private javax.swing.JLabel vfIntento;
    // End of variables declaration//GEN-END:variables
}
